export {default} from 'webpack'

export type {
  AssetInfo,
  Chunk,
  Compilation,
  Compiler,
  Configuration,
  DefinePlugin,
  HotModuleReplacementPlugin,
  MultiCompiler,
  MultiStats,
  PathData,
  ProvidePlugin,
  RuleSetRule,
  Stats,
  StatsAsset,
  StatsChunkGroup,
  StatsCompilation,
  StatsError,
  StatsModule,
  StatsOptions,
  StatsProfile,
  WebpackError,
  WebpackPluginInstance,
} from 'webpack'
