storage: /verdaccio/storage

auth:
  htpasswd:
    file: /verdaccio/config/verdaccio.auth

security:
  api:
    jwt:
      sign:
        expiresIn: 60d
        notBefore: 1
  web:
    sign:
      expiresIn: 7d

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@roots/*':
    access: $anonymous
    publish: $anonymous

  '**':
    access: $all
    publish: $all
    proxy: npmjs

logs:
  - {type: stdout, format: pretty, level: trace}
