entry:
  app: [app.js, app.css]
  editor: [editor.js]

entrypoints.setEmitHtml: true

eslint.extends:
  - ['@roots/eslint-config']

setPublicPath: /app/themes/your-theme-name/

tailwind.extend:
  colors:
    blue:
      100: '#ebf8ff'
      200: '#bee3f8'
      300: '#90cdf4'
      400: '#63b3ed'
      500: '#4299e1'

wpjson:
  enable: true
  useTailwindColors: true
