cacheFolder: config/yarn/cache

globalFolder: config/yarn/global

installStatePath: config/yarn/install-state.gz

nodeLinker: node-modules

npmRegistryServer: 'https://registry.npmjs.org'

plugins:
  - path: config/yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: config/yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: config/yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - dev/@bud/bundles/@yarnpkg/plugin-bud.js

pnpDataPath: config/pnp.data.json

pnpUnpluggedFolder: config/yarn/unplugged

virtualFolder: config/yarn/__virtual__

yarnPath: config/yarn/releases/yarn-3.1.1.cjs
