cacheFolder: .cache/yarn/yarn

enableMessageNames: false

globalFolder: .cache/yarn/global

installStatePath: .cache/yarn/install-state.gz

nodeLinker: node-modules

npmAuthIdent: 'test:test'

npmAuthToken: ''

npmPublishAccess: public

npmPublishRegistry: 'http://verdaccio:4873'

npmRegistryServer: 'http://verdaccio:4873'

plugins:
  - path: dev/yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: dev/yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: dev/yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - sources/yarn-plugin-bud/bundles/@yarnpkg/plugin-bud.js

pnpDataPath: dev/yarn/pnp.data.json

pnpUnpluggedFolder: dev/yarn/unplugged

unsafeHttpWhitelist:
  - verdaccio

virtualFolder: dev/yarn/__virtual__

yarnPath: dev/yarn/releases/yarn-3.1.1.cjs
