cacheFolder: cache/yarn

defaultSemverRangePrefix: ''

enableMessageNames: false

globalFolder: cache/global

installStatePath: cache/install-state.gz

nodeLinker: node-modules

npmPublishAccess: public

npmPublishRegistry: 'https://registry.npmjs.org/'

npmRegistryServer: 'https://registry.npmjs.org/'

plugins:
  - path: dev/yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: dev/yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: dev/yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - sources/yarn-plugin-bud/bundles/@yarnpkg/plugin-bud.js

pnpDataPath: dev/yarn/pnp.data.json

pnpUnpluggedFolder: dev/yarn/unplugged

virtualFolder: dev/yarn/__virtual__

yarnPath: dev/yarn/releases/yarn-3.1.1.cjs
