cacheFolder: config/yarn/cache

globalFolder: config/yarn/global

installStatePath: config/yarn/install-state.gz

nodeLinker: node-modules

npmAuthToken: ""

npmPublishAccess: public

npmPublishRegistry: "https://registry.npmjs.org/"

npmRegistries:
  "http://localhost:4873":
    npmAlwaysAuth: true
    npmAuthIdent: "roots:roots"

npmRegistryServer: "https://registry.npmjs.org/"

plugins:
  - path: bin/yarn/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: bin/yarn/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: bin/yarn/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - dev/@bud/bundles/@yarnpkg/plugin-bud.js

pnpDataPath: config/pnp.data.json

pnpUnpluggedFolder: config/yarn/unplugged

virtualFolder: config/yarn/__virtual__

yarnPath: bin/yarn/releases/yarn-3.1.1.cjs
