cacheFolder: storage/yarn/cache

compressionLevel: 0

defaultSemverRangePrefix: ""

enableGlobalCache: false

enableMessageNames: false

enableMirror: false

enableTelemetry: false

globalFolder: storage/yarn/global

installStatePath: storage/yarn/install-state.gz

nmMode: hardlinks-global

nodeLinker: node-modules

npmAuthToken: fallback

npmPublishAccess: public

npmPublishRegistry: "https://registry.npmjs.org"

npmRegistryServer: "https://registry.npmjs.org"

packageExtensions:
  "@docsearch/react@*":
    dependencies:
      "@algolia/client-search": "*"
    peerDependencies:
      "@algolia/client-search": "*"
    peerDependenciesMeta:
      "@algolia/client-search":
        optional: true
  "@netlify/build@*":
    dependencies:
      "@types/node": "*"
    peerDependencies:
      "@types/node": "*"
    peerDependenciesMeta:
      "@types/node":
        optional: true
  "@types/fork-ts-checker-webpack-plugin@*":
    dependencies:
      typescript: "*"
      webpack: "*"
    peerDependencies:
      typescript: "*"
      webpack: "*"
    peerDependenciesMeta:
      typescript:
        optional: true
      webpack:
        optional: true

plugins:
  - sources/@repo/yarn-plugin-bud/bundles/@yarnpkg/plugin-bud.js
  - sources/@repo/yarn-plugin-package/bundles/@yarnpkg/plugin-package.js

pnpUnpluggedFolder: .yarn/unplugged

preferInteractive: true

progressBarStyle: default

unsafeHttpWhitelist:
  - 0.0.0.0
  - localhost

virtualFolder: .yarn/__virtual__

yarnPath: .yarn/releases/yarn-4.0.2.cjs
