cacheFolder: storage/yarn/cache

defaultSemverRangePrefix: ""

enableMessageNames: false

enableTelemetry: false

globalFolder: storage/yarn/global

installStatePath: storage/yarn/install-state.gz

nodeLinker: node-modules

npmAuthToken: "${NPM_AUTH_TOKEN:-fallback}"

npmPublishAccess: public

npmPublishRegistry: "http://0.0.0.0:4873"

npmRegistryServer: "http://0.0.0.0:4873"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-tsconfig-references.cjs
    spec: "https://github.com/Dcard/yarn-plugins/releases/latest/download/plugin-tsconfig-references.js"
  - sources/@repo/yarn-plugin-bud/bundles/@yarnpkg/plugin-bud.js
  - sources/@repo/yarn-plugin-package/bundles/@yarnpkg/plugin-package.js
  - path: .yarn/plugins/@yarnpkg/plugin-stage.cjs
    spec: "@yarnpkg/plugin-stage"

pnpDataPath: .yarn/pnp.data.json

pnpUnpluggedFolder: .yarn/unplugged

progressBarStyle: default

unsafeHttpWhitelist:
  - 0.0.0.0
  - localhost

virtualFolder: .yarn/__virtual__

yarnPath: .yarn/releases/yarn-3.2.4.cjs
