cacheFolder: storage/yarn/cache

defaultSemverRangePrefix: ""

enableGlobalCache: true

enableMessageNames: true

enableMirror: false

enableTelemetry: false

globalFolder: storage/yarn/global

initFields:
  bugs: "https://github.com/roots/bud/issues"
  engines:
    node: ">=16"
  funding:
    type: github sponsors
    url: "https://github.com/sponsors/roots"
  keywords:
    - bud
  license: MIT

installStatePath: storage/yarn/install-state.gz

nmMode: hardlinks-global

nodeLinker: node-modules

npmAuthToken: fallback

npmPublishAccess: public

npmPublishRegistry: "https://registry.npmjs.org"

npmRegistryServer: "https://registry.npmjs.org"

packageExtensions:
  "@docsearch/react@*":
    dependencies:
      "@algolia/client-search": "*"
    peerDependencies:
      "@algolia/client-search": "*"
    peerDependenciesMeta:
      "@algolia/client-search":
        optional: true
  "@netlify/build@*":
    dependencies:
      "@types/node": "*"
    peerDependencies:
      "@types/node": "*"
    peerDependenciesMeta:
      "@types/node":
        optional: true
  "@types/fork-ts-checker-webpack-plugin@*":
    dependencies:
      typescript: "*"
      webpack: "*"
    peerDependencies:
      typescript: "*"
      webpack: "*"
    peerDependenciesMeta:
      typescript:
        optional: true
      webpack:
        optional: true
  "@types/wordpress__components@*":
    dependencies:
      react: "*"
      react-dom: "*"
    peerDependencies:
      react: "*"
      react-dom: "*"
    peerDependenciesMeta:
      react:
        optional: true
      react-dom:
        optional: true

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - sources/@repo/yarn-plugin-bud/bundles/@yarnpkg/plugin-bud.js
  - sources/@repo/yarn-plugin-package/bundles/@yarnpkg/plugin-package.js
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.cjs
    spec: "@yarnpkg/plugin-constraints"

pnpDataPath: .yarn/pnp.data.json

pnpUnpluggedFolder: .yarn/unplugged

preferInteractive: true

progressBarStyle: default

unsafeHttpWhitelist:
  - 0.0.0.0
  - localhost

virtualFolder: .yarn/__virtual__

yarnPath: .yarn/releases/yarn-3.3.1.cjs
