"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.vendor = exports.target = exports.template = exports.srcPath = exports.src = exports.string = exports.runtime = exports.run = exports.publicPath = exports.proxy = exports.provide = exports.projectPath = exports.project = exports.minify = exports.hash = exports.glob = exports.gzip = exports.externals = exports.entry = exports.distPath = exports.dist = exports.devtool = exports.dev = exports.define = exports.copy = exports.storage = exports.alias = exports.addPlugin = void 0;
var addPlugin_1 = require("./addPlugin");
Object.defineProperty(exports, "addPlugin", { enumerable: true, get: function () { return addPlugin_1.addPlugin; } });
var alias_1 = require("./alias");
Object.defineProperty(exports, "alias", { enumerable: true, get: function () { return alias_1.alias; } });
var storage_1 = require("./storage");
Object.defineProperty(exports, "storage", { enumerable: true, get: function () { return storage_1.storage; } });
var copy_1 = require("./copy");
Object.defineProperty(exports, "copy", { enumerable: true, get: function () { return copy_1.copy; } });
var define_1 = require("./define");
Object.defineProperty(exports, "define", { enumerable: true, get: function () { return define_1.define; } });
var dev_1 = require("./dev");
Object.defineProperty(exports, "dev", { enumerable: true, get: function () { return dev_1.dev; } });
var devtool_1 = require("./devtool");
Object.defineProperty(exports, "devtool", { enumerable: true, get: function () { return devtool_1.devtool; } });
var dist_1 = require("./dist");
Object.defineProperty(exports, "dist", { enumerable: true, get: function () { return dist_1.dist; } });
var distPath_1 = require("./distPath");
Object.defineProperty(exports, "distPath", { enumerable: true, get: function () { return distPath_1.distPath; } });
var entry_1 = require("./entry");
Object.defineProperty(exports, "entry", { enumerable: true, get: function () { return entry_1.entry; } });
var externals_1 = require("./externals");
Object.defineProperty(exports, "externals", { enumerable: true, get: function () { return externals_1.externals; } });
var gzip_1 = require("./gzip");
Object.defineProperty(exports, "gzip", { enumerable: true, get: function () { return gzip_1.gzip; } });
var glob_1 = require("./glob");
Object.defineProperty(exports, "glob", { enumerable: true, get: function () { return glob_1.glob; } });
var hash_1 = require("./hash");
Object.defineProperty(exports, "hash", { enumerable: true, get: function () { return hash_1.hash; } });
var minify_1 = require("./minify");
Object.defineProperty(exports, "minify", { enumerable: true, get: function () { return minify_1.minify; } });
var project_1 = require("./project");
Object.defineProperty(exports, "project", { enumerable: true, get: function () { return project_1.project; } });
var projectPath_1 = require("./projectPath");
Object.defineProperty(exports, "projectPath", { enumerable: true, get: function () { return projectPath_1.projectPath; } });
var provide_1 = require("./provide");
Object.defineProperty(exports, "provide", { enumerable: true, get: function () { return provide_1.provide; } });
var proxy_1 = require("./proxy");
Object.defineProperty(exports, "proxy", { enumerable: true, get: function () { return proxy_1.proxy; } });
var publicPath_1 = require("./publicPath");
Object.defineProperty(exports, "publicPath", { enumerable: true, get: function () { return publicPath_1.publicPath; } });
var run_1 = require("./run");
Object.defineProperty(exports, "run", { enumerable: true, get: function () { return run_1.run; } });
var runtime_1 = require("./runtime");
Object.defineProperty(exports, "runtime", { enumerable: true, get: function () { return runtime_1.runtime; } });
var string_1 = require("./string");
Object.defineProperty(exports, "string", { enumerable: true, get: function () { return string_1.string; } });
var src_1 = require("./src");
Object.defineProperty(exports, "src", { enumerable: true, get: function () { return src_1.src; } });
var srcPath_1 = require("./srcPath");
Object.defineProperty(exports, "srcPath", { enumerable: true, get: function () { return srcPath_1.srcPath; } });
var template_1 = require("./template");
Object.defineProperty(exports, "template", { enumerable: true, get: function () { return template_1.template; } });
var target_1 = require("./target");
Object.defineProperty(exports, "target", { enumerable: true, get: function () { return target_1.target; } });
var vendor_1 = require("./vendor");
Object.defineProperty(exports, "vendor", { enumerable: true, get: function () { return vendor_1.vendor; } });
//# sourceMappingURL=index.js.map