export {addPlugin} from './api/addPlugin'
export {alias} from './api/alias'
export {brotli} from './api/brotli'
export {buildCache} from './api/buildCache'
export {copy} from './api/copy'
export {define} from './api/define'
export {dev} from './api/dev'
export {devtool} from './api/devtool'
export {dist} from './api/dist'
export {distPath} from './api/distPath'
export {entry} from './api/entry'
export {externals} from './api/externals'
export {hash} from './api/hash'
export {gzip} from './api/gzip'
export {glob} from './api/glob'
export {library} from './api/library'
export {minify} from './api/minify'
export {project} from './api/project'
export {projectPath} from './api/projectPath'
export {provide} from './api/provide'
export {publicPath} from './api/publicPath'
export {run} from './api/run'
export {runtime} from './api/runtime'
export {src} from './api/src'
export {srcPath} from './api/srcPath'
export {template} from './api/template'
export {use} from './api/use'
export {target} from './api/target'
export {terser} from './api/terser'
export {vendor} from './api/vendor'
export {when} from './api/when'

export type {AddPlugin} from './api/addPlugin'
export type {Alias} from './api/alias'
export type {Brotli} from './api/brotli'
export type {BuildCache} from './api/buildCache'
export type {Copy} from './api/copy'
export type {Define} from './api/define'
export type {Dev} from './api/dev'
export type {Devtool} from './api/devtool'
