name: Feature Request
title: '[request] <title>'
description: Request a feature
labels: [request]

body:
  - type: checkboxes
    id: terms
    attributes:
      label: Agreement
      options:
        - label: This is not a duplicate of an existing issue
          required: true
        - label: I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
          required: true
        - label: This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community
          required: true

  - type: textarea
    id: description
    attributes:
      label: The feature
      placeholder: Describe what you think should be added.
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: Use case
      placeholder: How will this feature be useful? Who will it be useful for?
    validations:
      required: false

  - type: textarea
    id: other
    attributes:
      label: Notes
      placeholder: Anything else you'd like to add regarding this request.
    validations:
      required: false

  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this request form!
