export declare const ansiColors: {
    reset: string[];
    black: string;
    red: string;
    green: string;
    yellow: string;
    blue: string;
    magenta: string;
    cyan: string;
    lightgrey: string;
    darkgrey: string;
};
export declare const overlayStyles: {
    background: string;
    color: string;
    lineHeight: string;
    whiteSpace: string;
    fontFamily: string;
    fontSize: string;
    position: string;
    zIndex: number;
    overflow: string;
    padding: string;
    borderRadius: string;
    borderColor: string;
    left: number;
    right: number;
    top: number;
    bottom: number;
    textAlign: string;
    transition: string;
};
