export declare const babel = true;
export declare const postcss = true;
export declare const clean = true;
export declare const manifest = true;
export declare const html = false;
export declare const brotli = false;
export declare const gzip = false;
export declare const hash = false;
export declare const hot = false;
export declare const minify = false;
export declare const proxy = false;
export declare const splitChunks = false;
export declare const runtimeChunk = false;
export declare const overlay = false;
export declare const watch = false;
//# sourceMappingURL=features.d.ts.map