/**
 * This file is generated by {@link @roots/browserslist-config}
 */
module.exports = [
  `chrome 107`,
  `chrome 106`,
  `chrome 105`,
  `chrome 104`,
  `firefox 106`,
  `firefox 105`,
  `firefox 104`,
  `firefox 103`,
  `safari 16.1`,
  `safari 16.0`,
  `safari 15.6`,
  `safari 15.5`,
  `safari 15.4`,
  `safari 15.2-15.3`,
  `safari 15.1`,
  `safari 15`,
  `safari 14.1`,
  `safari 14`,
  `safari 13.1`,
  `safari 13`,
]
