/**
 * This file is generated by {@link @roots/browserslist-config}
 */
module.exports = [
  `chrome 107`,
  `chrome 106`,
  `firefox 106`,
  `firefox 105`,
  `safari 16.1`,
  `safari 16.0`,
  `safari 15.6`,
  `safari 15.5`,
  `safari 15.4`,
  `safari 15.2-15.3`,
  `safari 15.1`,
  `safari 15`,
]
