/**
 * This file is generated by @roots/browserslist-config
 */
module.exports = [
  `and_chr 106`,
  `and_ff 106`,
  `and_qq 13.1`,
  `and_uc 13.4`,
  `android 106`,
  `chrome 107`,
  `chrome 106`,
  `chrome 105`,
  `edge 106`,
  `edge 105`,
  `edge 104`,
  `firefox 106`,
  `firefox 105`,
  `firefox 104`,
  `ios_saf 16.1`,
  `ios_saf 16.0`,
  `ios_saf 15.6`,
  `kaios 2.5`,
  `op_mini all`,
  `op_mob 64`,
  `opera 91`,
  `opera 90`,
  `opera 89`,
  `safari 16.1`,
  `safari 16.0`,
  `safari 15.6`,
  `samsung 18.0`,
  `samsung 17.0`,
  `samsung 16.0`
]