nodeLinker: node-modules
plugins:
  - path: ../../dev/yarn/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: ../../dev/yarn/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
npmAuthToken: ''
npmAuthIdent: ''
npmRegistryServer: 'https://registry.npmjs.org/'
npmPublishRegistry: 'https://registry.npmjs.org/'
unsafeHttpWhitelist: []
