nodeLinker: node-modules
plugins:
  - path: ../../dev/yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: ../../dev/yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
npmRegistryServer: 'https://registry.npmjs.org/'
npmPublishRegistry: 'https://registry.npmjs.org/'
