const coreNodeModules = [
  'assert',
  'assert/strict',
  'async_hooks',
  'buffer',
  'child_process',
  'cluster',
  'console',
  'constants',
  'crypto',
  'dgram',
  'diagnostics_channel',
  'dns',
  'dns/promises',
  'domain',
  'events',
  'fs',
  'fs/promises',
  'http',
  'http2',
  'https',
  'inspector',
  'module',
  'net',
  'os',
  'path',
  'path/posix',
  'path/win32',
  'perf_hooks',
  'process',
  'punycode',
  'querystring',
  'readline',
  'readline/promises',
  'repl',
  'stream',
  'stream/consumers',
  'stream/promises',
  'stream/web',
  'string_decoder',
  'test',
  'test/reporters',
  'timers',
  'timers/promises',
  'tls',
  'trace_events',
  'tty',
  'url',
  'util',
  'util/types',
  'v8',
  'vm',
  'wasi',
  'worker_threads',
  'zlib',
]

type BuiltIns<K extends typeof coreNodeModules = typeof coreNodeModules> = {
  [Key in K as `${Key & string}` | `node:${Key & string}`]: false
}

const builtIns: Partial<BuiltIns> = coreNodeModules.reduce((a, b) => ({
  ...a,
  [`${b}`]: false,
  [`node:${b}`]: false,
}), {})

export {builtIns as default}
