/**
 * Syncpack configuration
 *
 * @see {@link https://github.com/JamieMason/syncpack#-configuration-file}
 */
module.exports = {
  dev: true,
  filter: `^(?!@roots/).*$`,
  indent: `  `,
  overrides: true,
  dependencyTypes: [`dev`, `prod`],
  pnpmOverrides: true,
  prod: true,
  resolutions: true,
  sortFirst: [
    `name`,
    `private`,
    `version`,
    `description`,
    `engines`,
    `packageManager`,
    `contributors`,
    `license`,
    `homepage`,
    `funding`,
    `repository`,
    `bugs`,
    `keywords`,
    `bin`,
    `files`,
    `type`,
    `exports`,
    `typesVersions`,
    `types`,
    `main`,
    `module`,
    `devDependencies`,
    `dependencies`,
    `peerDependencies`,
    `peerDependenciesMeta`,
    `optionalDependencies`,
    `bundledDependencies`,
    `resolutions`,
    `scripts`,
    `workspaces`,
    `bud`,
    `volta`,
  ],
  workspace: true,
  semverRange: ``,
  versionGroups: [
    {
      dependencies: [`**`],
      packages: [`@repo/docs`],
      label: `Docusaurus`,
    },
    {
      dependencies: [`**`],
      packages: [`issue-*`],
      label: `Test code (fixtures)`,
    },
    {
      dependencies: [`**`],
      packages: [`@example/*`],
      label: `Example code`,
    },
  ],
}
