listen: 0.0.0.0:4873

logs:
  - {type: stdout, format: pretty, level: trace}

packages:
  '@roots/*':
    access: $all
    publish: $all
    storage: '@roots'

  '**':
    access: $all
    publish: $all
    proxy: npmjs
    storage: 'npm'

storage: ../verdaccio/storage

uplinks:
  npmjs:
    url: https://registry.npmjs.org/
