storage: ../verdaccio
auth:
  htpasswd:
    file: ./verdaccio.auth

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@roots/*':
    access: $all
    publish: $all
    storage: '@roots'

  '**':
    access: $all
    publish: $all
    proxy: npmjs
    storage: 'npm'

logs:
  - {type: stdout, format: pretty, level: trace}
