cacheFolder: /bud/.cache/yarn

defaultSemverRangePrefix: ''

enableMessageNames: false

globalFolder: /bud/.cache/yarn/global

installStatePath: /bud/.cache/yarn/install-state.gz

nodeLinker: node-modules

npmAuthIdent: 'test:test'

npmAuthToken: ''

npmPublishAccess: public

npmPublishRegistry: 'http://verdaccio:4873'

npmRegistryServer: 'http://verdaccio:4873'

plugins:
  - path: /bud/dev/yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: /bud/dev/yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: /bud/dev/yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - /bud/sources/yarn-plugin-bud/bundles/@yarnpkg/plugin-bud.js

pnpDataPath: /bud/dev/yarn/pnp.data.json

pnpUnpluggedFolder: /bud/dev/yarn/unplugged

unsafeHttpWhitelist:
  - verdaccio

virtualFolder: /bud/dev/yarn/__virtual__

yarnPath: /bud/dev/yarn/releases/yarn-3.1.1.cjs
