export const nccOptions = {
  external: [
    'css-loader',
    'csv-loader',
    'file-loader',
    'html-loader',
    'remark-loader',
    'resolve-url-loader',
    'style-loader',
    'url-loader',
    'xml-loader',
  ],
  minify: false,
  sourceMap: false,
  sourceMapRegister: false,
  watch: false,
  v8cache: false,
  quiet: true,
  debugLog: false,
}
