export type {
  BabelTransformOptions,
  RuleSetLoader,
  WebpackCompiler,
  WebpackConfig,
  WebpackConfigFactory,
  WebpackDevMiddlewareOptions,
  WebpackEntry,
  WebpackExternals,
  WebpackMode,
  WebpackModule,
  WebpackOptimization,
  WebpackOptions,
  WebpackOutput,
  WebpackPlugins,
  WebpackResolve,
  WebpackTarget,
  WebpackRule,
} from './externals'
