/**
 * This file was automatically generated by bud.js using json-schema-to-typescript.
 * Do not edit this file directly.
 *
 * To update typings run:
 * `yarn workspace @roots/wordpress-theme-json-webpack-plugin exec node ./scripts/build-types.js`
 */

// @ts-nocheck
// eslint-disable

export type SettingsProperties = SettingsAppearanceToolsProperties &
  SettingsBackgroundProperties &
  SettingsBorderProperties &
  SettingsColorProperties &
  SettingsCustomProperties &
  SettingsDimensionsProperties &
  SettingsLayoutProperties &
  SettingsLightboxProperties &
  SettingsPositionProperties &
  SettingsShadowProperties &
  SettingsSpacingProperties &
  SettingsTypographyProperties
/**
 * This interface was referenced by `SettingsBlocksPropertiesComplete`'s JSON-Schema definition
 * via the `patternProperty` "^[a-z][a-z0-9-]*\/[a-z][a-z0-9-]*$".
 */
export type SettingsPropertiesComplete = {
  [k: string]: unknown
} & SettingsProperties
export type StylesPropertiesComplete = {
  [k: string]: unknown
} & StylesProperties
/**
 * This interface was referenced by `StylesBlocksPropertiesComplete`'s JSON-Schema definition
 * via the `patternProperty` "^[a-z][a-z0-9-]*\/[a-z][a-z0-9-]*$".
 */
export type StylesPropertiesAndElementsComplete = {
  [k: string]: unknown
  elements?: StylesElementsPropertiesComplete
  variations?: StylesVariationsPropertiesComplete
} & {
  [k: string]: unknown
} & StylesProperties
/**
 * This interface was referenced by `StylesVariationsPropertiesComplete`'s JSON-Schema definition
 * via the `patternProperty` "^[a-z][a-z0-9-]*$".
 */
export type StylesVariationPropertiesComplete = {
  [k: string]: unknown
  blocks?: StylesVariationBlocksPropertiesComplete
  elements?: StylesElementsPropertiesComplete
} & {
  [k: string]: unknown
} & StylesProperties
/**
 * This interface was referenced by `StylesVariationBlocksPropertiesComplete`'s JSON-Schema definition
 * via the `patternProperty` "^[a-z][a-z0-9-]*\/[a-z][a-z0-9-]*$".
 */
export type StylesVariationBlockPropertiesComplete = {
  [k: string]: unknown
  elements?: StylesElementsPropertiesComplete
} & {
  [k: string]: unknown
} & StylesProperties
/**
 * This interface was referenced by `StylesVariationsProperties`'s JSON-Schema definition
 * via the `patternProperty` "^[a-z][a-z0-9-]*$".
 */
export type StylesVariationProperties = {
  [k: string]: unknown
  blocks?: StylesVariationBlocksPropertiesComplete
  elements?: StylesElementsPropertiesComplete
} & {
  [k: string]: unknown
} & StylesProperties

export interface SettingsAndStyles {
  /**
   * JSON schema URI for theme.json.
   */
  $schema?: string
  /**
   * List of block types that can use the block style variation this theme.json file represents.
   */
  blockTypes?: string[]
  /**
   * Additional metadata for custom templates defined in the templates folder.
   */
  customTemplates?: {
    /**
     * Filename, without extension, of the template in the templates folder.
     */
    name: string
    /**
     * List of post types that can use this custom template.
     */
    postTypes?: string[]
    /**
     * Title of the template, translatable.
     */
    title: string
  }[]
  /**
   * Description of the global styles variation.
   */
  description?: string
  /**
   * An array of pattern slugs to be registered from the Pattern Directory.
   */
  patterns?: string[]
  /**
   * Settings for the block editor and individual blocks. These include things like:
   * - Which customization options should be available to the user.
   * - The default colors, font sizes... available to the user.
   * - CSS custom properties and class names used in styles.
   * - And the default layout of the editor (widths and available alignments).
   */
  settings?: {
    [k: string]: unknown
    blocks?: SettingsBlocksPropertiesComplete
    /**
     * Enables root padding (the values from `styles.spacing.padding`) to be applied to the contents of full-width blocks instead of the root block.
     *
     * Please note that when using this setting, `styles.spacing.padding` should always be set as an object with `top`, `right`, `bottom`, `left` values declared separately.
     */
    useRootPaddingAwareAlignments?: boolean
  } & {
    [k: string]: unknown
  } & SettingsProperties
  /**
   * Slug of the global styles variation. If not defined, the kebab-case title will be used.
   */
  slug?: string
  /**
   * Organized way to set CSS properties. Styles in the top-level will be added in the `body` selector.
   */
  styles?: {
    [k: string]: unknown
    blocks?: StylesBlocksPropertiesComplete
    elements?: StylesElementsPropertiesComplete
    variations?: StylesVariationsProperties
  } & {
    [k: string]: unknown
  } & StylesProperties
  /**
   * Additional metadata for template parts defined in the parts folder.
   */
  templateParts?: {
    /**
     * The area the template part is used for. Block variations for `header` and `footer` values exist and will be used when the area is set to one of those.
     */
    area?: string
    /**
     * Filename, without extension, of the template in the parts folder.
     */
    name: string
    /**
     * Title of the template, translatable.
     */
    title?: string
  }[]
  /**
   * Title of the global styles variation. If not defined, the file name will be used.
   */
  title?: string
  /**
   * Version of theme.json to use.
   */
  version: 3
}
export interface SettingsAppearanceToolsProperties {
  [k: string]: unknown
  /**
   * Setting that enables the following UI tools:
   *
   * - background: backgroundImage, backgroundSize
   * - border: color, radius, style, width
   * - color: link, heading, button, caption
   * - dimensions: aspectRatio, minHeight
   * - position: sticky
   * - spacing: blockGap, margin, padding
   * - typography: lineHeight
   */
  appearanceTools?: boolean
}
export interface SettingsBackgroundProperties {
  [k: string]: unknown
  /**
   * Settings related to background.
   */
  background?: {
    /**
     * Allow users to set a background image.
     */
    backgroundImage?: boolean
    /**
     * Allow users to set values related to the size of a background image, including size, position, and repeat controls.
     */
    backgroundSize?: boolean
  }
}
export interface SettingsBorderProperties {
  [k: string]: unknown
  /**
   * Settings related to borders.
   */
  border?: {
    /**
     * Allow users to set custom border colors.
     */
    color?: boolean
    /**
     * Allow users to set custom border radius.
     */
    radius?: boolean
    /**
     * Allow users to set custom border styles.
     */
    style?: boolean
    /**
     * Allow users to set custom border widths.
     */
    width?: boolean
  }
}
export interface SettingsColorProperties {
  [k: string]: unknown
  /**
   * Settings related to colors.
   */
  color?: {
    /**
     * Allow users to set background colors.
     */
    background?: boolean
    /**
     * Allow users to set button colors in a block.
     */
    button?: boolean
    /**
     * Allow users to set caption colors in a block.
     */
    caption?: boolean
    /**
     * Allow users to select custom colors.
     */
    custom?: boolean
    /**
     * Allow users to create custom duotone filters.
     */
    customDuotone?: boolean
    /**
     * Allow users to create custom gradients.
     */
    customGradient?: boolean
    /**
     * Allow users to choose filters from the default duotone filter presets.
     */
    defaultDuotone?: boolean
    /**
     * Allow users to choose colors from the default gradients.
     */
    defaultGradients?: boolean
    /**
     * Allow users to choose colors from the default palette.
     */
    defaultPalette?: boolean
    /**
     * Duotone presets for the duotone picker.
     * Doesn't generate classes or properties.
     */
    duotone?: {
      /**
       * List of colors from dark to light.
       */
      colors: string[]
      /**
       * Name of the duotone preset, translatable.
       */
      name: string
      /**
       * Kebab-case unique identifier for the duotone preset.
       */
      slug: string
    }[]
    /**
     * Gradient presets for the gradient picker.
     * Generates a single class (`.has-{slug}-background`) and custom property (`--wp--preset--gradient--{slug}`) per preset value.
     */
    gradients?: {
      /**
       * CSS gradient string.
       */
      gradient: string
      /**
       * Name of the gradient preset, translatable.
       */
      name: string
      /**
       * Kebab-case unique identifier for the gradient preset.
       */
      slug: string
    }[]
    /**
     * Allow users to set heading colors in a block.
     */
    heading?: boolean
    /**
     * Allow users to set link colors in a block.
     */
    link?: boolean
    /**
     * Color palette presets for the color picker.
     * Generates three classes (`.has-{slug}-color`, `.has-{slug}-background-color`, and `.has-{slug}-border-color`) and a single custom property (`--wp--preset--color--{slug}`) per preset value.
     */
    palette?: {
      /**
       * CSS hex or rgb(a) string.
       */
      color: string
      /**
       * Name of the color preset, translatable.
       */
      name: string
      /**
       * Kebab-case unique identifier for the color preset.
       */
      slug: string
    }[]
    /**
     * Allow users to set text colors in a block.
     */
    text?: boolean
  }
}
export interface SettingsDimensionsProperties {
  [k: string]: unknown
  /**
   * Settings related to dimensions.
   */
  dimensions?: {
    /**
     * Allow users to set an aspect ratio.
     */
    aspectRatio?: boolean
    /**
     * Allow users to define aspect ratios for some blocks.
     */
    aspectRatios?: {
      [k: string]: unknown
      /**
       * Name of the aspect ratio preset.
       */
      name?: string
      /**
       * Aspect ratio expressed as a division or decimal.
       */
      ratio?: string
      /**
       * Kebab-case unique identifier for the aspect ratio preset.
       */
      slug?: string
    }[]
    /**
     * Allow users to choose aspect ratios from the default set of aspect ratios.
     */
    defaultAspectRatios?: boolean
    /**
     * Allow users to set custom minimum height.
     */
    minHeight?: boolean
  }
}
export interface SettingsLayoutProperties {
  [k: string]: unknown
  /**
   * Settings related to layout.
   */
  layout?: {
    /**
     * Enable or disable the custom content and wide size controls.
     */
    allowCustomContentAndWideSize?: boolean
    /**
     * Disable the layout UI controls.
     */
    allowEditing?: boolean
    /**
     * Sets the max-width of the content.
     */
    contentSize?: string
    /**
     * Sets the max-width of wide (`.alignwide`) content. Also used as the maximum viewport when calculating fluid font sizes
     */
    wideSize?: string
  }
}
export interface SettingsLightboxProperties {
  [k: string]: unknown
  /**
   * Settings related to the lightbox.
   */
  lightbox?: {
    /**
     * Defines whether to show the Lightbox UI in the block editor. If set to `false`, the user won't be able to change the lightbox settings in the block editor.
     */
    allowEditing?: boolean
    /**
     * Defines whether the lightbox is enabled or not.
     */
    enabled?: boolean
  }
}
export interface SettingsPositionProperties {
  [k: string]: unknown
  /**
   * Settings related to position.
   */
  position?: {
    /**
     * Allow users to set sticky position.
     */
    sticky?: boolean
  }
}
export interface SettingsShadowProperties {
  [k: string]: unknown
  /**
   * Settings related to shadows.
   */
  shadow?: {
    /**
     * Allow users to choose shadows from the default shadow presets.
     */
    defaultPresets?: boolean
    /**
     * Shadow presets for the shadow picker.
     * Generates a single custom property (`--wp--preset--shadow--{slug}`) per preset value.
     */
    presets?: {
      /**
       * Name of the shadow preset, translatable.
       */
      name: string
      /**
       * CSS box-shadow value
       */
      shadow: string
      /**
       * Kebab-case unique identifier for the shadow preset.
       */
      slug: string
    }[]
  }
}
export interface SettingsSpacingProperties {
  [k: string]: unknown
  /**
   * Settings related to spacing.
   */
  spacing?: {
    /**
     * Enables `--wp--style--block-gap` to be generated from styles.spacing.blockGap.
     * A value of `null` instead of `false` further disables layout styles from being generated.
     */
    blockGap?: boolean | null
    /**
     * Allow users to set custom space sizes.
     */
    customSpacingSize?: boolean
    /**
     * Allow users to choose space sizes from the default space size presets.
     */
    defaultSpacingSizes?: boolean
    /**
     * Allow users to set a custom margin.
     */
    margin?: boolean
    /**
     * Allow users to set a custom padding.
     */
    padding?: boolean
    /**
     * Settings to auto-generate space size presets for the space size selector.
     * Generates a custom property (--wp--preset--spacing--{slug}`) per preset value.
     */
    spacingScale?: {
      /**
       * The amount to increment each step by.
       */
      increment?: number
      /**
       * The value to medium setting in the scale.
       */
      mediumStep?: number
      /**
       * With + or * depending on whether scale is generated by increment or multiplier.
       */
      operator?: '*' | '+'
      /**
       * Number of steps to generate in scale.
       */
      steps?: number
      /**
       * Unit that the scale uses, eg. rem, em, px.
       */
      unit?:
        | '%'
        | 'dvb'
        | 'dvh'
        | 'dvi'
        | 'dvmax'
        | 'dvmin'
        | 'dvw'
        | 'em'
        | 'lvb'
        | 'lvh'
        | 'lvi'
        | 'lvmax'
        | 'lvmin'
        | 'lvw'
        | 'px'
        | 'rem'
        | 'svb'
        | 'svh'
        | 'svi'
        | 'svmax'
        | 'svmin'
        | 'svw'
        | 'vb'
        | 'vh'
        | 'vi'
        | 'vmax'
        | 'vmin'
        | 'vw'
    }
    /**
     * Space size presets for the space size selector.
     * Generates a custom property (`--wp--preset--spacing--{slug}`) per preset value.
     */
    spacingSizes?: {
      /**
       * Name of the space size preset, translatable.
       */
      name?: string
      /**
       * CSS space-size value, including units.
       */
      size?: string
      /**
       * Unique identifier for the space size preset. For best cross theme compatibility these should be in the form '10','20','30','40','50','60', etc. with '50' representing the 'Medium' size step. If all slugs begin with a number they will be merged with default and user slugs and sorted numerically.
       */
      slug?: string
    }[]
    /**
     * List of units the user can use for spacing values.
     *
     * @minItems 1
     */
    units?: [string, ...string[]]
  }
}
export interface SettingsTypographyProperties {
  [k: string]: unknown
  /**
   * Settings related to typography.
   */
  typography?: {
    /**
     * Allow users to set custom font sizes.
     */
    customFontSize?: boolean
    /**
     * Allow users to choose font sizes from the default font size presets.
     */
    defaultFontSizes?: boolean
    /**
     * Enable drop cap.
     */
    dropCap?: boolean
    /**
     * Enables fluid typography and allows users to set global fluid typography parameters.
     */
    fluid?:
      | {
          /**
           * Allow users to set custom a max viewport width in px, rem or em, used to set the maximum size boundary of a fluid font size.
           */
          maxViewportWidth?: string
          /**
           * Allow users to set a global minimum font size boundary in px, rem or em. Custom font sizes below this value will not be clamped, and all calculated minimum font sizes will be, at a minimum, this value.
           */
          minFontSize?: string
          /**
           * Allow users to set a custom min viewport width in px, rem or em, used to set the minimum size boundary of a fluid font size.
           */
          minViewportWidth?: string
        }
      | boolean
    /**
     * Font family presets for the font family selector.
     * Generates a single custom property (`--wp--preset--font-family--{slug}`) per preset value.
     */
    fontFamilies?: {
      /**
       * Array of font-face declarations.
       */
      fontFace?: {
        /**
         * CSS ascent-override value.
         */
        ascentOverride?: string
        /**
         * CSS descent-override value.
         */
        descentOverride?: string
        /**
         * CSS font-display value.
         */
        fontDisplay?: 'auto' | 'block' | 'fallback' | 'optional' | 'swap'
        /**
         * CSS font-family value.
         */
        fontFamily: string
        /**
         * CSS font-feature-settings value.
         */
        fontFeatureSettings?: string
        /**
         * CSS font-stretch value.
         */
        fontStretch?: string
        /**
         * CSS font-style value.
         */
        fontStyle?: string
        /**
         * CSS font-variant value.
         */
        fontVariant?: string
        /**
         * CSS font-variation-settings value.
         */
        fontVariationSettings?: string
        /**
         * List of available font weights, separated by a space.
         */
        fontWeight?: number | string
        /**
         * CSS line-gap-override value.
         */
        lineGapOverride?: string
        /**
         * CSS size-adjust value.
         */
        sizeAdjust?: string
        /**
         * Paths or URLs to the font files.
         */
        src: string | string[]
        /**
         * CSS unicode-range value.
         */
        unicodeRange?: string
      }[]
      /**
       * CSS font-family value.
       */
      fontFamily?: string
      /**
       * Name of the font family preset, translatable.
       */
      name?: string
      /**
       * Kebab-case unique identifier for the font family preset.
       */
      slug?: string
    }[]
    /**
     * Font size presets for the font size selector.
     * Generates a single class (`.has-{slug}-color`) and custom property (`--wp--preset--font-size--{slug}`) per preset value.
     */
    fontSizes?: {
      /**
       * Specifies the minimum and maximum font size value of a fluid font size. Set to `false` to bypass fluid calculations and use the static `size` value.
       */
      fluid?:
        | {
            /**
             * A max font size for fluid font size calculations in px, rem or em.
             */
            max?: string
            /**
             * A min font size for fluid font size calculations in px, rem or em.
             */
            min?: string
          }
        | boolean
      /**
       * Name of the font size preset, translatable.
       */
      name?: string
      /**
       * CSS font-size value, including units.
       */
      size?: string
      /**
       * Kebab-case unique identifier for the font size preset.
       */
      slug?: string
    }[]
    /**
     * Allow users to set custom font styles.
     */
    fontStyle?: boolean
    /**
     * Allow users to set custom font weights.
     */
    fontWeight?: boolean
    /**
     * Allow users to set custom letter spacing.
     */
    letterSpacing?: boolean
    /**
     * Allow users to set custom line height.
     */
    lineHeight?: boolean
    /**
     * Allow users to set the text align.
     */
    textAlign?: boolean
    /**
     * Allow users to set the number of text columns.
     */
    textColumns?: boolean
    /**
     * Allow users to set custom text decorations.
     */
    textDecoration?: boolean
    /**
     * Allow users to set custom text transforms.
     */
    textTransform?: boolean
    /**
     * Allow users to set the writing mode.
     */
    writingMode?: boolean
  }
}
export interface SettingsCustomProperties {
  [k: string]: unknown
  custom?: SettingsCustomAdditionalProperties
}
/**
 * Generate custom CSS custom properties of the form `--wp--custom--{key}--{nested-key}: {value};`. `camelCased` keys are transformed to `kebab-case` as to follow the CSS property naming schema. Keys at different depth levels are separated by `--`, so keys should not include `--` in the name.
 */
export interface SettingsCustomAdditionalProperties {
  [k: string]: number | SettingsCustomAdditionalProperties | string
}
/**
 * Settings defined on a per-block basis.
 */
export interface SettingsBlocksPropertiesComplete {
  [k: string]: SettingsPropertiesComplete
  'core/archives'?: SettingsPropertiesComplete
  'core/audio'?: SettingsPropertiesComplete
  'core/avatar'?: SettingsPropertiesComplete
  'core/block'?: SettingsPropertiesComplete
  'core/button'?: SettingsPropertiesComplete
  'core/buttons'?: SettingsPropertiesComplete
  'core/calendar'?: SettingsPropertiesComplete
  'core/categories'?: SettingsPropertiesComplete
  'core/code'?: SettingsPropertiesComplete
  'core/column'?: SettingsPropertiesComplete
  'core/columns'?: SettingsPropertiesComplete
  'core/comment-author-avatar'?: SettingsPropertiesComplete
  'core/comment-author-name'?: SettingsPropertiesComplete
  'core/comment-content'?: SettingsPropertiesComplete
  'core/comment-date'?: SettingsPropertiesComplete
  'core/comment-edit-link'?: SettingsPropertiesComplete
  'core/comment-reply-link'?: SettingsPropertiesComplete
  'core/comment-template'?: SettingsPropertiesComplete
  'core/comments'?: SettingsPropertiesComplete
  'core/comments-pagination'?: SettingsPropertiesComplete
  'core/comments-pagination-next'?: SettingsPropertiesComplete
  'core/comments-pagination-numbers'?: SettingsPropertiesComplete
  'core/comments-pagination-previous'?: SettingsPropertiesComplete
  'core/comments-title'?: SettingsPropertiesComplete
  'core/cover'?: SettingsPropertiesComplete
  'core/details'?: SettingsPropertiesComplete
  'core/embed'?: SettingsPropertiesComplete
  'core/file'?: SettingsPropertiesComplete
  'core/freeform'?: SettingsPropertiesComplete
  'core/gallery'?: SettingsPropertiesComplete
  'core/group'?: SettingsPropertiesComplete
  'core/heading'?: SettingsPropertiesComplete
  'core/home-link'?: SettingsPropertiesComplete
  'core/html'?: SettingsPropertiesComplete
  'core/image'?: SettingsPropertiesComplete
  'core/latest-comments'?: SettingsPropertiesComplete
  'core/latest-posts'?: SettingsPropertiesComplete
  'core/legacy-widget'?: SettingsPropertiesComplete
  'core/list'?: SettingsPropertiesComplete
  'core/list-item'?: SettingsPropertiesComplete
  'core/loginout'?: SettingsPropertiesComplete
  'core/media-text'?: SettingsPropertiesComplete
  'core/missing'?: SettingsPropertiesComplete
  'core/more'?: SettingsPropertiesComplete
  'core/navigation'?: SettingsPropertiesComplete
  'core/navigation-link'?: SettingsPropertiesComplete
  'core/navigation-submenu'?: SettingsPropertiesComplete
  'core/nextpage'?: SettingsPropertiesComplete
  'core/page-list'?: SettingsPropertiesComplete
  'core/page-list-item'?: SettingsPropertiesComplete
  'core/paragraph'?: SettingsPropertiesComplete
  'core/post-author'?: SettingsPropertiesComplete
  'core/post-author-biography'?: SettingsPropertiesComplete
  'core/post-author-name'?: SettingsPropertiesComplete
  'core/post-comment'?: SettingsPropertiesComplete
  'core/post-comments-count'?: SettingsPropertiesComplete
  'core/post-comments-form'?: SettingsPropertiesComplete
  'core/post-comments-link'?: SettingsPropertiesComplete
  'core/post-content'?: SettingsPropertiesComplete
  'core/post-date'?: SettingsPropertiesComplete
  'core/post-excerpt'?: SettingsPropertiesComplete
  'core/post-featured-image'?: SettingsPropertiesComplete
  'core/post-navigation-link'?: SettingsPropertiesComplete
  'core/post-template'?: SettingsPropertiesComplete
  'core/post-terms'?: SettingsPropertiesComplete
  'core/post-time-to-read'?: SettingsPropertiesComplete
  'core/post-title'?: SettingsPropertiesComplete
  'core/preformatted'?: SettingsPropertiesComplete
  'core/pullquote'?: SettingsPropertiesComplete
  'core/query'?: SettingsPropertiesComplete
  'core/query-no-results'?: SettingsPropertiesComplete
  'core/query-pagination'?: SettingsPropertiesComplete
  'core/query-pagination-next'?: SettingsPropertiesComplete
  'core/query-pagination-numbers'?: SettingsPropertiesComplete
  'core/query-pagination-previous'?: SettingsPropertiesComplete
  'core/query-title'?: SettingsPropertiesComplete
  'core/quote'?: SettingsPropertiesComplete
  'core/read-more'?: SettingsPropertiesComplete
  'core/rss'?: SettingsPropertiesComplete
  'core/search'?: SettingsPropertiesComplete
  'core/separator'?: SettingsPropertiesComplete
  'core/shortcode'?: SettingsPropertiesComplete
  'core/site-logo'?: SettingsPropertiesComplete
  'core/site-tagline'?: SettingsPropertiesComplete
  'core/site-title'?: SettingsPropertiesComplete
  'core/social-link'?: SettingsPropertiesComplete
  'core/social-links'?: SettingsPropertiesComplete
  'core/spacer'?: SettingsPropertiesComplete
  'core/table'?: SettingsPropertiesComplete
  'core/table-of-contents'?: SettingsPropertiesComplete
  'core/tag-cloud'?: SettingsPropertiesComplete
  'core/template-part'?: SettingsPropertiesComplete
  'core/term-description'?: SettingsPropertiesComplete
  'core/text-columns'?: SettingsPropertiesComplete
  'core/verse'?: SettingsPropertiesComplete
  'core/video'?: SettingsPropertiesComplete
  'core/widget-area'?: SettingsPropertiesComplete
  'core/widget-group'?: SettingsPropertiesComplete
}
export interface StylesProperties {
  [k: string]: unknown
  /**
   * Background styles.
   */
  background?: {
    /**
     * Sets the `background-attachment` CSS property.
     */
    backgroundAttachment?: RefComplete | string
    /**
     * Sets the `background-image` CSS property.
     */
    backgroundImage?:
      | {
          /**
           * A URL to an image file, or a path to a file relative to the theme root directory, and prefixed with `file:`, e.g., 'file:./path/to/file.png'.
           */
          url?: string
        }
      | RefComplete
      | string
    /**
     * Sets the `background-position` CSS property.
     */
    backgroundPosition?: RefComplete | string
    /**
     * Sets the `background-repeat` CSS property.
     */
    backgroundRepeat?: RefComplete | string
    /**
     * Sets the `background-size` CSS property.
     */
    backgroundSize?: RefComplete | string
  }
  /**
   * Border styles.
   */
  border?: {
    bottom?: {
      /**
       * Sets the `border-bottom-color` CSS property.
       */
      color?: RefComplete | string
      /**
       * Sets the `border-bottom-style` CSS property.
       */
      style?: RefComplete | string
      /**
       * Sets the `border-bottom-width` CSS property.
       */
      width?: RefComplete | string
    }
    /**
     * Sets the `border-color` CSS property.
     */
    color?: RefComplete | string
    left?: {
      /**
       * Sets the `border-left-color` CSS property.
       */
      color?: RefComplete | string
      /**
       * Sets the `border-left-style` CSS property.
       */
      style?: RefComplete | string
      /**
       * Sets the `border-left-width` CSS property.
       */
      width?: RefComplete | string
    }
    /**
     * Sets the `border-radius` CSS property.
     */
    radius?:
      | {
          [k: string]: unknown
          /**
           * Sets the `border-bottom-left-radius` CSS property.
           */
          bottomLeft?: RefComplete | string
          /**
           * Sets the `border-bottom-right-radius` CSS property.
           */
          bottomRight?: RefComplete | string
          /**
           * Sets the `border-top-left-radius` CSS property.
           */
          topLeft?: RefComplete | string
          /**
           * Sets the `border-top-right-radius` CSS property.
           */
          topRight?: RefComplete | string
        }
      | RefComplete
      | string
    right?: {
      /**
       * Sets the `border-right-color` CSS property.
       */
      color?: RefComplete | string
      /**
       * Sets the `border-right-style` CSS property.
       */
      style?: RefComplete | string
      /**
       * Sets the `border-right-width` CSS property.
       */
      width?: RefComplete | string
    }
    /**
     * Sets the `border-style` CSS property.
     */
    style?: RefComplete | string
    top?: {
      /**
       * Sets the `border-top-color` CSS property.
       */
      color?: RefComplete | string
      /**
       * Sets the `border-top-style` CSS property.
       */
      style?: RefComplete | string
      /**
       * Sets the `border-top-width` CSS property.
       */
      width?: RefComplete | string
    }
    /**
     * Sets the `border-width` CSS property.
     */
    width?: RefComplete | string
  }
  /**
   * Color styles.
   */
  color?: {
    /**
     * Sets the `background-color` CSS property.
     */
    background?: RefComplete | string
    /**
     * Sets the `background` CSS property.
     */
    gradient?: RefComplete | string
    /**
     * Sets the `color` CSS property.
     */
    text?: RefComplete | string
  }
  /**
   * Sets custom CSS to apply styling not covered by other theme.json properties.
   */
  css?: string
  /**
   * Dimensions styles.
   */
  dimensions?: {
    [k: string]: unknown
    /**
     * Sets the `aspect-ratio` CSS property.
     */
    aspectRatio?: RefComplete | string
    /**
     * Sets the `min-height` CSS property.
     */
    minHeight?: RefComplete | string
  }
  /**
   * CSS and SVG filter styles.
   */
  filter?: {
    /**
     * Sets the duotone filter.
     */
    duotone?: RefComplete | string
  }
  /**
   * Outline styles.
   */
  outline?: {
    /**
     * Sets the `outline-color` CSS property.
     */
    color?: RefComplete | string
    /**
     * Sets the `outline-offset` CSS property.
     */
    offset?: RefComplete | string
    /**
     * Sets the `outline-style` CSS property.
     */
    style?: RefComplete | string
    /**
     * Sets the `outline-width` CSS property.
     */
    width?: RefComplete | string
  }
  /**
   * Box shadow styles.
   */
  shadow?: RefComplete | string
  /**
   * Spacing styles.
   */
  spacing?: {
    /**
     * Sets the `--wp--style--block-gap` CSS custom property when settings.spacing.blockGap is true.
     */
    blockGap?: RefComplete | string
    /**
     * Margin styles.
     */
    margin?: {
      /**
       * Sets the `margin-bottom` CSS property.
       */
      bottom?: RefComplete | string
      /**
       * Sets the `margin-left` CSS property.
       */
      left?: RefComplete | string
      /**
       * Sets the `margin-right` CSS property.
       */
      right?: RefComplete | string
      /**
       * Sets the `margin-top` CSS property.
       */
      top?: RefComplete | string
    }
    /**
     * Padding styles.
     */
    padding?: {
      /**
       * Sets the `padding-bottom` CSS property.
       */
      bottom?: RefComplete | string
      /**
       * Sets the `padding-left` CSS property.
       */
      left?: RefComplete | string
      /**
       * Sets the `padding-right` CSS property.
       */
      right?: RefComplete | string
      /**
       * Sets the `padding-top` CSS property.
       */
      top?: RefComplete | string
    }
  }
  /**
   * Typography styles.
   */
  typography?: {
    /**
     * Sets the `font-family` CSS property.
     */
    fontFamily?: RefComplete | string
    /**
     * Sets the `font-size` CSS property.
     */
    fontSize?: RefComplete | string
    /**
     * Sets the `font-style` CSS property.
     */
    fontStyle?: RefComplete | string
    /**
     * Sets the `font-weight` CSS property.
     */
    fontWeight?: RefComplete | string
    /**
     * Sets the `letter-spacing` CSS property.
     */
    letterSpacing?: RefComplete | string
    /**
     * Sets the `line-height` CSS property.
     */
    lineHeight?: RefComplete | string
    /**
     * Sets the `text-align` CSS property.
     */
    textAlign?: RefComplete | string
    /**
     * Sets the `column-count` CSS property.
     */
    textColumns?: RefComplete | string
    /**
     * Sets the `text-decoration` CSS property.
     */
    textDecoration?: RefComplete | string
    /**
     * Sets the `text-transform` CSS property.
     */
    textTransform?: RefComplete | string
    /**
     * Sets the `writing-mode` CSS property.
     */
    writingMode?: RefComplete | string
  }
}
export interface RefComplete {
  /**
   * A reference to another property value. e.g. `styles.color.text`
   */
  ref?: string
}
/**
 * Styles defined on a per-element basis using the element's selector.
 */
export interface StylesElementsPropertiesComplete {
  button?: {
    [k: string]: unknown
  } & StylesElementsPseudoSelectorsProperties &
    StylesProperties
  caption?: StylesPropertiesComplete
  cite?: StylesPropertiesComplete
  h1?: StylesPropertiesComplete
  h2?: StylesPropertiesComplete
  h3?: StylesPropertiesComplete
  h4?: StylesPropertiesComplete
  h5?: StylesPropertiesComplete
  h6?: StylesPropertiesComplete
  heading?: StylesPropertiesComplete
  link?: {
    [k: string]: unknown
  } & StylesElementsPseudoSelectorsProperties &
    StylesProperties
}
export interface StylesElementsPseudoSelectorsProperties {
  ':active'?: StylesPropertiesComplete
  ':any-link'?: StylesPropertiesComplete
  ':focus'?: StylesPropertiesComplete
  ':hover'?: StylesPropertiesComplete
  ':link'?: StylesPropertiesComplete
  ':visited'?: StylesPropertiesComplete
  [k: string]: unknown
}
/**
 * Styles defined on a per-block basis using the block's selector.
 */
export interface StylesBlocksPropertiesComplete {
  [k: string]: StylesPropertiesAndElementsComplete
  'core/archives'?: StylesPropertiesAndElementsComplete
  'core/audio'?: StylesPropertiesAndElementsComplete
  'core/avatar'?: StylesPropertiesAndElementsComplete
  'core/block'?: StylesPropertiesAndElementsComplete
  'core/button'?: StylesPropertiesAndElementsComplete
  'core/buttons'?: StylesPropertiesAndElementsComplete
  'core/calendar'?: StylesPropertiesAndElementsComplete
  'core/categories'?: StylesPropertiesAndElementsComplete
  'core/code'?: StylesPropertiesAndElementsComplete
  'core/column'?: StylesPropertiesAndElementsComplete
  'core/columns'?: StylesPropertiesAndElementsComplete
  'core/comment-author-avatar'?: StylesPropertiesAndElementsComplete
  'core/comment-author-name'?: StylesPropertiesAndElementsComplete
  'core/comment-content'?: StylesPropertiesAndElementsComplete
  'core/comment-date'?: StylesPropertiesAndElementsComplete
  'core/comment-edit-link'?: StylesPropertiesAndElementsComplete
  'core/comment-reply-link'?: StylesPropertiesAndElementsComplete
  'core/comment-template'?: StylesPropertiesAndElementsComplete
  'core/comments'?: StylesPropertiesAndElementsComplete
  'core/comments-pagination'?: StylesPropertiesAndElementsComplete
  'core/comments-pagination-next'?: StylesPropertiesAndElementsComplete
  'core/comments-pagination-numbers'?: StylesPropertiesAndElementsComplete
  'core/comments-pagination-previous'?: StylesPropertiesAndElementsComplete
  'core/comments-title'?: StylesPropertiesAndElementsComplete
  'core/cover'?: StylesPropertiesAndElementsComplete
  'core/details'?: StylesPropertiesAndElementsComplete
  'core/embed'?: StylesPropertiesAndElementsComplete
  'core/file'?: StylesPropertiesAndElementsComplete
  'core/freeform'?: StylesPropertiesAndElementsComplete
  'core/gallery'?: StylesPropertiesAndElementsComplete
  'core/group'?: StylesPropertiesAndElementsComplete
  'core/heading'?: StylesPropertiesAndElementsComplete
  'core/home-link'?: StylesPropertiesAndElementsComplete
  'core/html'?: StylesPropertiesAndElementsComplete
  'core/image'?: StylesPropertiesAndElementsComplete
  'core/latest-comments'?: StylesPropertiesAndElementsComplete
  'core/latest-posts'?: StylesPropertiesAndElementsComplete
  'core/legacy-widget'?: StylesPropertiesAndElementsComplete
  'core/list'?: StylesPropertiesAndElementsComplete
  'core/list-item'?: StylesPropertiesAndElementsComplete
  'core/loginout'?: StylesPropertiesAndElementsComplete
  'core/media-text'?: StylesPropertiesAndElementsComplete
  'core/missing'?: StylesPropertiesAndElementsComplete
  'core/more'?: StylesPropertiesAndElementsComplete
  'core/navigation'?: StylesPropertiesAndElementsComplete
  'core/navigation-link'?: StylesPropertiesAndElementsComplete
  'core/navigation-submenu'?: StylesPropertiesAndElementsComplete
  'core/nextpage'?: StylesPropertiesAndElementsComplete
  'core/page-list'?: StylesPropertiesAndElementsComplete
  'core/page-list-item'?: StylesPropertiesAndElementsComplete
  'core/paragraph'?: StylesPropertiesAndElementsComplete
  'core/post-author'?: StylesPropertiesAndElementsComplete
  'core/post-author-biography'?: StylesPropertiesAndElementsComplete
  'core/post-author-name'?: StylesPropertiesAndElementsComplete
  'core/post-comment'?: StylesPropertiesAndElementsComplete
  'core/post-comments-count'?: StylesPropertiesAndElementsComplete
  'core/post-comments-form'?: StylesPropertiesAndElementsComplete
  'core/post-comments-link'?: StylesPropertiesAndElementsComplete
  'core/post-content'?: StylesPropertiesAndElementsComplete
  'core/post-date'?: StylesPropertiesAndElementsComplete
  'core/post-excerpt'?: StylesPropertiesAndElementsComplete
  'core/post-featured-image'?: StylesPropertiesAndElementsComplete
  'core/post-navigation-link'?: StylesPropertiesAndElementsComplete
  'core/post-template'?: StylesPropertiesAndElementsComplete
  'core/post-terms'?: StylesPropertiesAndElementsComplete
  'core/post-time-to-read'?: StylesPropertiesAndElementsComplete
  'core/post-title'?: StylesPropertiesAndElementsComplete
  'core/preformatted'?: StylesPropertiesAndElementsComplete
  'core/pullquote'?: StylesPropertiesAndElementsComplete
  'core/query'?: StylesPropertiesAndElementsComplete
  'core/query-no-results'?: StylesPropertiesAndElementsComplete
  'core/query-pagination'?: StylesPropertiesAndElementsComplete
  'core/query-pagination-next'?: StylesPropertiesAndElementsComplete
  'core/query-pagination-numbers'?: StylesPropertiesAndElementsComplete
  'core/query-pagination-previous'?: StylesPropertiesAndElementsComplete
  'core/query-title'?: StylesPropertiesAndElementsComplete
  'core/quote'?: StylesPropertiesAndElementsComplete
  'core/read-more'?: StylesPropertiesAndElementsComplete
  'core/rss'?: StylesPropertiesAndElementsComplete
  'core/search'?: StylesPropertiesAndElementsComplete
  'core/separator'?: StylesPropertiesAndElementsComplete
  'core/shortcode'?: StylesPropertiesAndElementsComplete
  'core/site-logo'?: StylesPropertiesAndElementsComplete
  'core/site-tagline'?: StylesPropertiesAndElementsComplete
  'core/site-title'?: StylesPropertiesAndElementsComplete
  'core/social-link'?: StylesPropertiesAndElementsComplete
  'core/social-links'?: StylesPropertiesAndElementsComplete
  'core/spacer'?: StylesPropertiesAndElementsComplete
  'core/table'?: StylesPropertiesAndElementsComplete
  'core/table-of-contents'?: StylesPropertiesAndElementsComplete
  'core/tag-cloud'?: StylesPropertiesAndElementsComplete
  'core/template-part'?: StylesPropertiesAndElementsComplete
  'core/term-description'?: StylesPropertiesAndElementsComplete
  'core/text-columns'?: StylesPropertiesAndElementsComplete
  'core/verse'?: StylesPropertiesAndElementsComplete
  'core/video'?: StylesPropertiesAndElementsComplete
  'core/widget-area'?: StylesPropertiesAndElementsComplete
  'core/widget-group'?: StylesPropertiesAndElementsComplete
}
export interface StylesVariationsPropertiesComplete {
  [k: string]: StylesVariationPropertiesComplete
}
export interface StylesVariationBlocksPropertiesComplete {
  [k: string]: StylesVariationBlockPropertiesComplete
  'core/archives'?: StylesVariationBlockPropertiesComplete
  'core/audio'?: StylesVariationBlockPropertiesComplete
  'core/avatar'?: StylesVariationBlockPropertiesComplete
  'core/block'?: StylesVariationBlockPropertiesComplete
  'core/button'?: StylesVariationBlockPropertiesComplete
  'core/buttons'?: StylesVariationBlockPropertiesComplete
  'core/calendar'?: StylesVariationBlockPropertiesComplete
  'core/categories'?: StylesVariationBlockPropertiesComplete
  'core/code'?: StylesVariationBlockPropertiesComplete
  'core/column'?: StylesVariationBlockPropertiesComplete
  'core/columns'?: StylesVariationBlockPropertiesComplete
  'core/comment-author-avatar'?: StylesVariationBlockPropertiesComplete
  'core/comment-author-name'?: StylesVariationBlockPropertiesComplete
  'core/comment-content'?: StylesVariationBlockPropertiesComplete
  'core/comment-date'?: StylesVariationBlockPropertiesComplete
  'core/comment-edit-link'?: StylesVariationBlockPropertiesComplete
  'core/comment-reply-link'?: StylesVariationBlockPropertiesComplete
  'core/comment-template'?: StylesVariationBlockPropertiesComplete
  'core/comments'?: StylesVariationBlockPropertiesComplete
  'core/comments-pagination'?: StylesVariationBlockPropertiesComplete
  'core/comments-pagination-next'?: StylesVariationBlockPropertiesComplete
  'core/comments-pagination-numbers'?: StylesVariationBlockPropertiesComplete
  'core/comments-pagination-previous'?: StylesVariationBlockPropertiesComplete
  'core/comments-title'?: StylesVariationBlockPropertiesComplete
  'core/cover'?: StylesVariationBlockPropertiesComplete
  'core/details'?: StylesVariationBlockPropertiesComplete
  'core/embed'?: StylesVariationBlockPropertiesComplete
  'core/file'?: StylesVariationBlockPropertiesComplete
  'core/freeform'?: StylesVariationBlockPropertiesComplete
  'core/gallery'?: StylesVariationBlockPropertiesComplete
  'core/group'?: StylesVariationBlockPropertiesComplete
  'core/heading'?: StylesVariationBlockPropertiesComplete
  'core/home-link'?: StylesVariationBlockPropertiesComplete
  'core/html'?: StylesVariationBlockPropertiesComplete
  'core/image'?: StylesVariationBlockPropertiesComplete
  'core/latest-comments'?: StylesVariationBlockPropertiesComplete
  'core/latest-posts'?: StylesVariationBlockPropertiesComplete
  'core/legacy-widget'?: StylesVariationBlockPropertiesComplete
  'core/list'?: StylesVariationBlockPropertiesComplete
  'core/list-item'?: StylesVariationBlockPropertiesComplete
  'core/loginout'?: StylesVariationBlockPropertiesComplete
  'core/media-text'?: StylesVariationBlockPropertiesComplete
  'core/missing'?: StylesVariationBlockPropertiesComplete
  'core/more'?: StylesVariationBlockPropertiesComplete
  'core/navigation'?: StylesVariationBlockPropertiesComplete
  'core/navigation-link'?: StylesVariationBlockPropertiesComplete
  'core/navigation-submenu'?: StylesVariationBlockPropertiesComplete
  'core/nextpage'?: StylesVariationBlockPropertiesComplete
  'core/page-list'?: StylesVariationBlockPropertiesComplete
  'core/page-list-item'?: StylesVariationBlockPropertiesComplete
  'core/paragraph'?: StylesVariationBlockPropertiesComplete
  'core/post-author'?: StylesVariationBlockPropertiesComplete
  'core/post-author-biography'?: StylesVariationBlockPropertiesComplete
  'core/post-author-name'?: StylesVariationBlockPropertiesComplete
  'core/post-comment'?: StylesVariationBlockPropertiesComplete
  'core/post-comments-count'?: StylesVariationBlockPropertiesComplete
  'core/post-comments-form'?: StylesVariationBlockPropertiesComplete
  'core/post-comments-link'?: StylesVariationBlockPropertiesComplete
  'core/post-content'?: StylesVariationBlockPropertiesComplete
  'core/post-date'?: StylesVariationBlockPropertiesComplete
  'core/post-excerpt'?: StylesVariationBlockPropertiesComplete
  'core/post-featured-image'?: StylesVariationBlockPropertiesComplete
  'core/post-navigation-link'?: StylesVariationBlockPropertiesComplete
  'core/post-template'?: StylesVariationBlockPropertiesComplete
  'core/post-terms'?: StylesVariationBlockPropertiesComplete
  'core/post-time-to-read'?: StylesVariationBlockPropertiesComplete
  'core/post-title'?: StylesVariationBlockPropertiesComplete
  'core/preformatted'?: StylesVariationBlockPropertiesComplete
  'core/pullquote'?: StylesVariationBlockPropertiesComplete
  'core/query'?: StylesVariationBlockPropertiesComplete
  'core/query-no-results'?: StylesVariationBlockPropertiesComplete
  'core/query-pagination'?: StylesVariationBlockPropertiesComplete
  'core/query-pagination-next'?: StylesVariationBlockPropertiesComplete
  'core/query-pagination-numbers'?: StylesVariationBlockPropertiesComplete
  'core/query-pagination-previous'?: StylesVariationBlockPropertiesComplete
  'core/query-title'?: StylesVariationBlockPropertiesComplete
  'core/quote'?: StylesVariationBlockPropertiesComplete
  'core/read-more'?: StylesVariationBlockPropertiesComplete
  'core/rss'?: StylesVariationBlockPropertiesComplete
  'core/search'?: StylesVariationBlockPropertiesComplete
  'core/separator'?: StylesVariationBlockPropertiesComplete
  'core/shortcode'?: StylesVariationBlockPropertiesComplete
  'core/site-logo'?: StylesVariationBlockPropertiesComplete
  'core/site-tagline'?: StylesVariationBlockPropertiesComplete
  'core/site-title'?: StylesVariationBlockPropertiesComplete
  'core/social-link'?: StylesVariationBlockPropertiesComplete
  'core/social-links'?: StylesVariationBlockPropertiesComplete
  'core/spacer'?: StylesVariationBlockPropertiesComplete
  'core/table'?: StylesVariationBlockPropertiesComplete
  'core/table-of-contents'?: StylesVariationBlockPropertiesComplete
  'core/tag-cloud'?: StylesVariationBlockPropertiesComplete
  'core/template-part'?: StylesVariationBlockPropertiesComplete
  'core/term-description'?: StylesVariationBlockPropertiesComplete
  'core/text-columns'?: StylesVariationBlockPropertiesComplete
  'core/verse'?: StylesVariationBlockPropertiesComplete
  'core/video'?: StylesVariationBlockPropertiesComplete
  'core/widget-area'?: StylesVariationBlockPropertiesComplete
  'core/widget-group'?: StylesVariationBlockPropertiesComplete
}
export interface StylesVariationsProperties {
  [k: string]: StylesVariationProperties
}
