"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.optimization = exports.resolve = exports.plugins = exports.output = exports.externals = exports.module = exports.general = exports.entry = void 0;
var entry_1 = require("./entry");
Object.defineProperty(exports, "entry", { enumerable: true, get: function () { return entry_1.entry; } });
var general_1 = require("./general");
Object.defineProperty(exports, "general", { enumerable: true, get: function () { return general_1.general; } });
var module_1 = require("./module");
Object.defineProperty(exports, "module", { enumerable: true, get: function () { return module_1.moduleBuilder; } });
var externals_1 = require("./externals");
Object.defineProperty(exports, "externals", { enumerable: true, get: function () { return externals_1.externals; } });
var output_1 = require("./output");
Object.defineProperty(exports, "output", { enumerable: true, get: function () { return output_1.output; } });
var plugins_1 = require("./plugins");
Object.defineProperty(exports, "plugins", { enumerable: true, get: function () { return plugins_1.plugins; } });
var resolve_1 = require("./resolve");
Object.defineProperty(exports, "resolve", { enumerable: true, get: function () { return resolve_1.resolve; } });
var optimization_1 = require("./optimization");
Object.defineProperty(exports, "optimization", { enumerable: true, get: function () { return optimization_1.optimization; } });
//# sourceMappingURL=index.js.map