export {entry} from './entry'
export {general} from './general'
export {moduleBuilder as module} from './module'
export {externals} from './externals'
export {output} from './output'
export {plugins} from './plugins'
export {resolve} from './resolve'
export {optimization} from './optimization'
