storage: ../../storage

auth:
  htpasswd:
    file: .htpasswd

security:
  api:
    jwt:
      sign:
        expiresIn: 60d
        notBefore: 1
  web:
    sign:
      expiresIn: 7d

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@roots/*':
    access: $all
    publish: $all
    unpublish: $all
    storage: 'packages'

  '**':
    access: $all
    publish: $all
    proxy: npmjs
    storage: 'packages/npm'

logs:
  - {type: stdout, format: pretty, level: info}
