export {method as alias} from './alias'
export {method as assets} from './assets'
export {config} from './config'
export {define} from './define'
export {devtool} from './devtool'
export {entry} from './entry'
export {experiments} from './experiments'
export {externals} from './externals'
export {hash} from './hash'
export {minimize} from './minimize'
export {persist} from './persist'
export {provide} from './provide'
export {proxy} from './proxy'
export {publicPath} from './publicPath'
export {run} from './run'
export {runtime} from './runtime'
export {serve} from './serve'
export {setPublicPath} from './setPublicPath'
export {splitChunks} from './splitChunks'
export {template} from './template'
export {use} from './use'
export {watch} from './watch'
