module.exports = {
  packages: [
    '@roots/container',
    '@roots/bud-dashboard',
    '@roots/bud-support',
    '@roots/wordpress-dependencies-webpack-plugin',
    '@roots/wordpress-externals-webpack-plugin',
    '@roots/entrypoints-webpack-plugin',
    '@roots/bud-support',
    '@roots/bud-framework',
  ],
  options: {
    externals: [
      'css-loader',
      'csv-loader',
      'file-loader',
      'html-loader',
      'remark-loasder',
      'resolve-url-loader',
      'style-loader',
      'typescript',
      'uglify-js',
      'webpack',
      'url-loader',
      'xml-loader',
      '@roots/bud-framework',
      '@roots/bud-support',
    ],
    cache: false,
    minify: false,
    sourceMap: false,
    sourceMapRegister: false,
    watch: false,
    v8cache: false,
    debugLog: false,
  },
}
