import {join} from 'node:path'

// eslint-disable-next-line
import {paths} from '@repo/constants'
import {execa} from 'execa'
import fs from 'fs-jetpack'

const comment = `/**\n * This file is generated by {@link @roots/browserslist-config}\n */`

const path = filename =>
  join(paths.sources, `@roots`, `browserslist-config`, filename)

const queryList = async query =>
  await execa(`yarn`, [`browserslist`, query.join(`,`)]).then(
    ({stdout}) => stdout,
  )

const toArray = str => str.split(`\n`).map(str => str.trim())

const toString = arr =>
  JSON.stringify(arr, null, 2)
    .replaceAll(`"`, `\``)
    .replace(`\`\n`, `\`,\n`)

export const generate = async (filename, versions) => {
  const browsers = await queryList(versions).then(toArray).then(toString)

  await fs.writeAsync(
    path(filename),
    `${comment}\nmodule.exports = ${browsers}\n`,
  )
}
