import {join} from 'node:path'

import {paths} from '@repo/constants'
import {execa} from '@roots/bud-support/execa'
import fs from '@roots/bud-support/fs-jetpack'

export const generate = async (filename, versions) => {
  const {stdout} = await execa(`yarn`, [
    `browserslist`,
    versions.join(`,`),
  ])

  const browsers = stdout
    .trim()
    .split(`\n`)
    .map(str => str.trim())

  await fs.write(
    join(paths.sources, `@roots`, `browserslist-config`, filename),
    `\
/**
 * This file is generated by @roots/browserslist-config
 */
module.exports = ${JSON.stringify(browsers, null, 2)}`.replaceAll(
      `"`,
      `\``,
    ),
  )
}
