name: Deploy docs

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
          cache: yarn

      - name: yarn
        run: yarn

      - name: yarn @bud build
        run: yarn @bud build

      - name: yarn @bud docs
        run: yarn @bud docs

      - name: Deploy to netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.DEV_NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=sources/@repo/docs/build --prod
