name: Release latest version

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version number (x.y.z format)
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
          cache: yarn

      - name: set npmAuthToken
        run: |
          yarn config set npmAuthToken ${{ secrets.NODE_AUTH_TOKEN }}

      - name: Set npmPublishRegistry
        run: yarn config set npmPublishRegistry https://registry.npmjs.org

      - name: Set npmRegistryServer
        run: yarn config set npmRegistryServer https://registry.npmjs.org

      - name: Release v${{ github.event.inputs.version }}
        run: yarn @bud release --tag latest --version ${{ github.event.inputs.version }}

      - name: Reset npmAuthToken
        run: yarn config set npmAuthToken "${NPM_AUTH_TOKEN:-fallback}"

      - name: Configure Git
        run: |
          git config user.name "Roots Ladybud"
          git config user.email "<>"

      - name: Create v${{ github.event.inputs.version }} branch
        run: git checkout -b v${{ github.event.inputs.version }}

      - name: Commit v${{ github.event.inputs.version }}
        run: |
          git commit -am "chore: Bump @roots/bud to v${{ github.event.inputs.version }}"
          git push -u origin v${{ github.event.inputs.version }}

      - name: Tag v${{ github.event.inputs.version }}
        run: |
          git tag v${{ github.event.inputs.version }}
          git push --tags
