export {alias} from '@roots/bud-api/methods/alias'
export {assets, assets as copy} from '@roots/bud-api/methods/assets'
export {bundle} from '@roots/bud-api/methods/bundle'
export {compilePaths} from '@roots/bud-api/methods/compilePaths'
export {
  config,
  config as webpackConfig,
  config as override,
} from '@roots/bud-api/methods/config'
export {copyDir} from '@roots/bud-api/methods/copyDir'
export {copyFile} from '@roots/bud-api/methods/copyFile'
export {define} from '@roots/bud-api/methods/define'
export {devtool} from '@roots/bud-api/methods/devtool'
export {entry} from '@roots/bud-api/methods/entry'
export {experiments} from '@roots/bud-api/methods/experiments'
export {externals} from '@roots/bud-api/methods/externals'
export {hash, hash as version} from '@roots/bud-api/methods/hash'
export {html, html as template} from '@roots/bud-api/methods/html'
export {minimize} from '@roots/bud-api/methods/minimize'
export {persist} from '@roots/bud-api/methods/persist'
export {provide} from '@roots/bud-api/methods/provide'
export {proxy} from '@roots/bud-api/methods/proxy'
export {runtime} from '@roots/bud-api/methods/runtime'
export {serve} from '@roots/bud-api/methods/serve'
export {setProxyUrl} from '@roots/bud-api/methods/setProxyUrl'
export {setPublicProxyUrl} from '@roots/bud-api/methods/setPublicProxyUrl'
export {setPublicUrl} from '@roots/bud-api/methods/setPublicUrl'
export {setUrl} from '@roots/bud-api/methods/setUrl'
export {splitChunks} from '@roots/bud-api/methods/splitChunks'
export {use} from '@roots/bud-api/methods/use'
export {watch} from '@roots/bud-api/methods/watch'
