export {alias} from './alias/index.js'
export {assets, assets as copy} from './assets/index.js'
export {bundle} from './bundle/index.js'
export {
  config,
  config as webpackConfig,
  config as override,
} from './config/index.js'
export {copyDir} from './copyDir/index.js'
export {copyFile} from './copyFile/index.js'
export {define} from './define/index.js'
export {devtool} from './devtool/index.js'
export {entry} from './entry/index.js'
export {experiments} from './experiments/index.js'
export {externals} from './externals/index.js'
export {hash, hash as version} from './hash/index.js'
export {html, html as template} from './html/index.js'
export {minimize} from './minimize/index.js'
export {persist} from './persist/index.js'
export {provide} from './provide/index.js'
export {proxy} from './proxy/index.js'
export {compilePaths} from './compilePaths/index.js'
export {runtime} from './runtime/index.js'
export {serve} from './serve/index.js'
export {setPublicUrl} from './setPublicUrl/index.js'
export {setProxyUrl} from './setProxyUrl/index.js'
export {setPublicProxyUrl} from './setPublicProxyUrl/index.js'
export {setUrl} from './setUrl/index.js'
export {splitChunks} from './splitChunks/index.js'
export {use} from './use/index.js'
export {watch} from './watch/index.js'
